format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_31_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_32_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_33_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_34_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_42_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_43_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_44_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_45_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_46_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_52_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_53_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_54_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_55_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_58_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_59_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_60_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_61_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_63_DIR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: String
    attributes: {id: BSP_PIN_63_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_64_DIR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Out}
  - type: String
    attributes: {id: BSP_PIN_64_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED1}
  - type: String
    attributes: {id: BSP_PIN_64_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GPIO}
  - type: String
    attributes: {id: BSP_PIN_64_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_7_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Combo
    attributes: {id: CONFIG_ICESEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ICS_PGx2}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_4_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: TIMER_1_InterruptHandler}
  - type: File
    attributes: {id: EVIC_INT_ASM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Hex
    attributes: {id: PMD4_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '4294967294'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '4294967293'}
  - type: Hex
    attributes: {id: SYS_PORT_E_ANSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16'}
  - type: Hex
    attributes: {id: SYS_PORT_E_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16'}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: 'true'}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: TIMER_1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: TIMER_1_InterruptHandler}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: 'true'}
  - type: Boolean
    attributes: {id: TMR1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: 'true'}
  - type: Integer
    attributes: {id: TMR1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: core}
