format_version: v1.0
type: UniqueComponent
attributes: {id: uart1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '25'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '1'}
  - type: Comment
    attributes: {id: UART_BRGH_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Standard Speed mode 16x baud clock enabled (BRGH
            = 0) ***'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '48000000'}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '340', y: '20', id: uart1}
