configName: pic32mx_xlp_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX274F256D
projectName: ''
settings:
  PackageFilter: bsp;core;csp;gfx;motor_control;validation;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.1.215\atdf\PIC32MX274F256D.atdf
