format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '120'}
  - type: Comment
    attributes: {id: TIMER_32BIT_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TIMER_32BIT_MODE_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '312500'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '4294967295'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '312499'}
  - type: KeyValueSet
    attributes: {id: TIMER_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1.3743895E7'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1000.0'}
  - type: String
    attributes: {id: TMR_IEC_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IEC0}
  - type: String
    attributes: {id: TMR_IFS_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IFS0}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'false'}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '256'}
  - type: Boolean
    attributes: {id: TMR_SLAVE_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'true'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: tmr2}
