format_version: v1.0
type: UniqueComponent
attributes: {id: i2c1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '475'}
  - type: Boolean
    attributes: {id: I2CS_A10M_SUPPORT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '14'}
  - type: KeyValueSet
    attributes: {id: I2CS_SETUP_RISE_TIME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '4'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '48000000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '50000'}
  - type: Boolean
    attributes: {id: I2C_INCLUDE_FORCED_WRITE_API}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: I2C_MASTER_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: I2C_MASTER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: I2C_MASTER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Combo
    attributes: {id: I2C_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Slave}
  - type: Hex
    attributes: {id: I2C_SLAVE_ADDDRESS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: I2C Slave Address (7-bit)}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: I2C_SLAVE_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: I2C_SLAVE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: I2C_SLAVE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: i2c1}
