format_version: v1.0
type: UniqueComponent
attributes: {id: ocmp3}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: OCMP_OCxCON_OCM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Long
    attributes: {id: OCMP_OCxR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '15000'}
  - type: Hex
    attributes: {id: OCxCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ocmp3, value: '3'}
- type: ElementPosition
  attributes: {x: '315', y: '48', id: ocmp3}
