format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '112'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '140625'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '14061'}
  - type: KeyValueSet
    attributes: {id: TIMER_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '466.0409'}
    - type: Values
      children:
      - type: User
        attributes: {value: '100.0'}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '256'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: tmr2}
