format_version: v1.0
type: UniqueComponent
attributes: {id: spi1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SPIS_SLAVE_SELECT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '17'}
- type: ElementPosition
  attributes: {x: '130', y: '71', id: spi1}
