format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_12_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_13_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_18_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_1_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_2_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_32_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_35_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_37_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_38_DIR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Out}
  - type: String
    attributes: {id: BSP_PIN_38_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED}
  - type: String
    attributes: {id: BSP_PIN_38_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GPIO}
  - type: String
    attributes: {id: BSP_PIN_38_LAT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: High}
  - type: String
    attributes: {id: BSP_PIN_38_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_3_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_41_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_42_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_43_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_44_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_4_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_5_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'true'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: CORE_TIMER_InterruptHandler}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_0_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: CORE_TIMER_InterruptHandler}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '65537'}
  - type: Hex
    attributes: {id: SYS_PORT_C_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32'}
  - type: Hex
    attributes: {id: SYS_PORT_C_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: core}
