format_version: v1.0
type: UniqueComponent
attributes: {id: core_timer}
children:
- type: Symbols
  children:
  - type: Float
    attributes: {id: CORE_TIMER_COMPARE_MS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '48000000'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CORE_TIMER_PERIODIC_INTERRUPT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Float
    attributes: {id: CORE_TIMER_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1000.0'}
  - type: Integer
    attributes: {id: CORE_TIMER_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '1000000'}
  - type: String
    attributes: {id: CORE_TIMER_PERIOD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '0x2dc6c00'}
- type: ElementPosition
  attributes: {x: '340', y: '20', id: core_timer}
