format_version: v1.0
type: UniqueComponent
attributes: {id: ocmp3}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: OCMP_OCxCON_OCM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Long
    attributes: {id: OCMP_OCxRS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: OCMP_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: OCxCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ocmp3, value: '5'}
- type: ElementPosition
  attributes: {x: '201', y: '138', id: ocmp3}
