format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_31_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_32_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_33_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_34_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_42_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_43_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_44_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_45_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_46_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_52_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_53_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_54_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_55_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_58_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: U1TX}
  - type: String
    attributes: {id: BSP_PIN_58_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_59_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: U1RX}
  - type: String
    attributes: {id: BSP_PIN_59_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_5_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: C1INC}
  - type: String
    attributes: {id: BSP_PIN_60_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_61_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_63_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_7_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: Boolean
    attributes: {id: CMP1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: 'true'}
  - type: Boolean
    attributes: {id: CMP2_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: 'true'}
  - type: Boolean
    attributes: {id: COMPARATOR_1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: 'true'}
  - type: Boolean
    attributes: {id: COMPARATOR_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: COMPARATOR_1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: COMPARATOR_1_InterruptHandler}
  - type: Boolean
    attributes: {id: COMPARATOR_1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cmp, value: 'true'}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Combo
    attributes: {id: CONFIG_ICESEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ICS_PGx2}
  - type: Boolean
    attributes: {id: CVR_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cvr, value: 'true'}
  - type: Integer
    attributes: {id: CVR_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: String
    attributes: {id: CoreMainFileName}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: main}
  - type: Boolean
    attributes: {id: EVIC_27_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_27_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_27_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: COMPARATOR_1_InterruptHandler}
  - type: Boolean
    attributes: {id: EVIC_31_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_31_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: EVIC_31_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: UART_1_Handler}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Hex
    attributes: {id: PMD1_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '257'}
  - type: Hex
    attributes: {id: PMD2_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: PMD5_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16974622'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '65537'}
  - type: Combo
    attributes: {id: SYS_PORT_PPS_INPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: U1RX}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_INPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '18'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Combo
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: RPF0}
  - type: Boolean
    attributes: {id: UART1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'true'}
  - type: Integer
    attributes: {id: UART1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: UART_1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: UART_1_Handler}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Boolean
    attributes: {id: USE_PPS_INPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: core}
