configName: pic32mx470_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../../..
processor: PIC32MX470F512H
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32cm_mc00;crypto;cryptoauthlib;csp;csp_apps_pic32cm_mc00;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.4.240\atdf\PIC32MX470F512H.atdf
