files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 173A89FF2267EE770AE1E7C5838EB9FC
  logicalPath: config\pic32mx_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 173A89FF2267EE770AE1E7C5838EB9FC
- generatedChecksum: 89B2CF6741179C3D45BA8E6CACFE3B0E
  logicalPath: config\pic32mx_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 89B2CF6741179C3D45BA8E6CACFE3B0E
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 6902DD0021DA94F42DE165233780733C
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6902DD0021DA94F42DE165233780733C
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: B9075C50D6E5312528847AA1098C60AD
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9075C50D6E5312528847AA1098C60AD
- generatedChecksum: BCB30EFD47515B1291A715D31B307C9A
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: BCB30EFD47515B1291A715D31B307C9A
- generatedChecksum: 9DC717E61F1E3A5706308EA5F885E204
  logicalPath: config\pic32mx_sk\peripheral\wdt
  name: plib_wdt.c
  physicalPath: peripheral\wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9DC717E61F1E3A5706308EA5F885E204
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mx_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: AC976C677A183CEA4E0196E2A20DBD64
  logicalPath: config\pic32mx_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: AC976C677A183CEA4E0196E2A20DBD64
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A3649BD56F9B6583F2E2A3ED24B543E6
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: A3649BD56F9B6583F2E2A3ED24B543E6
- generatedChecksum: 08CAE57066302D12E2A32EE07E935AFE
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 08CAE57066302D12E2A32EE07E935AFE
- generatedChecksum: 289F35AD623593FC40A0F73142869219
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 289F35AD623593FC40A0F73142869219
- generatedChecksum: CE6EC097E60ED6A31224837752B229EF
  logicalPath: config\pic32mx_sk\peripheral\wdt
  name: plib_wdt.h
  physicalPath: peripheral\wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: CE6EC097E60ED6A31224837752B229EF
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: D3313458AC706756FC68F2CE1408ECFF
  logicalPath: config\pic32mx_sk
  name: p32MX360F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: D3313458AC706756FC68F2CE1408ECFF
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
