configName: pic32mx_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX360F512L
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_usb;bsp;core;core_apps_pic32cm_jh00_jh01;core_apps_pic32cx_bz24_bz25;core_apps_sam_c20_c21;core_apps_sam_g55;core_apps_sam_l21;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_le_ls;csp_apps_pic32cm_mc00;csp_apps_pic32cx_bz24_bz25;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_ef;csp_apps_pic32mz_w1;csp_apps_sam_c20_c21;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_g55;csp_apps_sam_ha1;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.4.241\atdf\PIC32MX360F512L.atdf
  MERGE_STRATEGY: USER_ALL
